L-BFGS
to266/optimize pull request #12
Opened 2018-11-12 13:03 UTC by sebasv

Implements a limited-memory BFGS variant. First step towards an L-BFGS-B routine.

2018-11-20 07:33 UTC, sebasv commented
Ready for review. Currently uses the golden ratio line search to determine step size, we could consider a trust region as well.

2018-11-28 21:19 UTC, to266 requested changes
LGTM, just one trivial comment below.

Thanks for the PR!

2018-11-28 21:19 UTC, to266 commented on src/vector/l_bfgs.rs
> +                let min = ::scalar::GoldenRatioBuilder::default()
How about moving this minimizer implementation outside the loop? Not sure this works, but I don't see any obvious reasons why not.

2018-12-01 16:47 UTC, to266 approved these changes

2018-12-01 16:48 UTC, merged